repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
    - id: dart-format
      name: Check dart format
      description: Check that dart files are correctly formatted
      entry: ./dart-format-check
      language: python
      files: ".*\\.dart"
      stages: [pre-commit]
