name: "Build & Test"

on:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
        #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

        #2 setup java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

        #3 setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

        #4 install dependencies
      - name: Install Dependencies
        run: flutter pub get --disable-telemetry

        #5 build
      - name: Build flutter app
        run: flutter build apk

        #5 run unit test
      - name: Test flutter app
        run: flutter test
