name: "Build & Test"

on:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      - name: Disable telemetry
        run: flutter  --disable-telemetry

      - name: Install Dependencies
        run: flutter pub get

      - name: Build flutter app
        run: flutter build apk

      - name: Test flutter app
        run: flutter test
